Release 0.10.0
prometheus-community/smartctl_exporter pull request #142
Opened 2023-08-10 13:03 UTC by k0ste

* [FEATURE] Add device include/exclude filters for the automatic scanning #99
* [ENHANCEMENT] Critical metrics for SCSI disks added #131
* [CHANGE] Remove duplicate smartctl_device_status metric #137
* [CHANGE] Fix reported Data bytes Read/Written on SSDs #138
* [FEATURE] Add background scanning for devices #140
* [ENHANCEMENT] Added device name to logger rc code parser #141

2023-08-10 13:03 UTC, k0ste commented
@NiceGuyIT 🙏

2023-08-10 13:14 UTC, NiceGuyIT commented
@k0ste I was going to see if we can include PR #138 before doing a release.

2023-08-10 13:17 UTC, frittentheke commented
> @k0ste I was going to see if we can include PR #138 before doing a release.

@NiceGuyIT  ... what about https://github.com/prometheus-community/smartctl_exporter/pull/137 ... provided it's valid, it seems like a small cleanup as well.

2023-08-10 15:02 UTC, SuperQ requested changes

2023-08-10 15:02 UTC, SuperQ commented on CHANGELOG.md
> +## 0.9.2 / 2023-06-10
Patch releases are for `[BUGFIX]` only.

```suggestion
## 0.10.0 / 2023-06-10
```

2023-08-10 19:03 UTC, k0ste commented
> @k0ste Can you make the requested changes and add the other merged PRs?

Done ✅

2023-08-12 08:27 UTC, NiceGuyIT commented
@SuperQ Do I merge this release PR and then `git tag` the master branch with the new VERSION to kick off the build process? Is there anything I should watch out for or pay attention to during the release process?

2023-08-12 08:32 UTC, SuperQ commented
@NiceGuyIT Yup, that's all you need to do. Checkout the `tag-release` git config alias in the Prometheus RELEASES docs.

The only thing to check is that the build publishes the releases to draft and contains the release artifacts.

2023-08-12 09:26 UTC, merged

2023-08-12 10:13 UTC, NiceGuyIT commented
Thanks @SuperQ! Release 0.10.0 is out. Now I can help with the releases going forward.