Critical metrics for SCSI disks added
prometheus-community/smartctl_exporter pull request #21
Opened 2021-04-18 22:11 UTC by wwwlde

Added the following metrics for SCSI disks:

- Grown Defect List
- Read Errors Corrected by ReReads/ReWrites
- Read Total Uncorrected Errors
- Write Errors Corrected by ReReads/ReWrites
- Write Total Uncorrected Errors

2022-10-14 05:10 UTC, k0ste commented
@wwwlde can you rebase this PR?
Thanks!

2022-12-08 15:02 UTC, Nexucis commented
@wwwlde do you want to finish this PR.
It looks like it is waited by many users, would be cool to see this one merge !

2022-12-08 16:05 UTC, wwwlde commented
@Nexucis Done!

2022-12-09 15:10 UTC, Nexucis reviewed
it looks ok to me, but I don't have much knowledge around this topic.
@SuperQ could look at this PR and say if you have anything against merging it ?

2022-12-09 21:05 UTC, SuperQ commented
Yikes, the rebase created a merge mess.

2022-12-09 21:07 UTC, SuperQ requested changes

2022-12-09 21:07 UTC, SuperQ commented on smartctl.go
> +			prometheus.CounterValue,
This either needs to be a `GaugeValue`, or the metric name needs to end in `_total`.

Same goes for all the other metrics.

2023-08-10 10:23 UTC, k0ste commented
@wwwlde now this merged to master and can be closed
Thanks!

2023-08-10 10:49 UTC, Nexucis commented
closing this PR in favor of #131 

Thanks for your help here @wwwlde !

2023-08-10 10:49 UTC, closed without merging