fix: allow configuring powermode check to work better with SSDs
prometheus-community/smartctl_exporter pull request #242
Opened 2024-09-09 22:30 UTC by rbjorklin

By setting `--nocheck=never` I can correctly scrape SMART metrics from SSDs that report a `standby` power state:
```shell
# hdparm -C /dev/sda

/dev/sda:
 drive state is:  standby
 ```

fixes #91

2024-11-08 08:07 UTC, SuperQ requested changes
In order to avoid invalid string injection, would you please add a `switch` statement in main.go to validate input of the flag?

2025-01-14 21:35 UTC, denyago commented
I hope one would fix & merge this pr. 🙏 

I've got the same issue with a USB drive.

Fixed it by adding a UDEV rule:
```
ACTION=="add", SUBSYSTEM=="usb", ATTR{power/autosuspend}="0"
```

2025-04-03 12:13 UTC, k0ste commented
Fixes #287

2025-04-21 17:46 UTC, rbjorklin commented
@NiceGuyIT could I bother you to review and merge this?

2025-04-22 01:12 UTC, merged

2025-04-22 01:16 UTC, NiceGuyIT commented
@rbjorklin Done!

Thanks for the nudge. :)